### ISSUE TITLE
Crash When target Core (modular unit) 

### ISSUE THREAD

**Issue by ShardedFilms** [AvantTeam/ProjectUnityPublic#12]
LOG 2/8/2022

java.lang.NullPointerException
	at unity.gen.ModularUnitUnit.lambda$update$11(ModularUnitUnit.java:1845)
	at arc.struct.Seq.each(Seq.java:199)
	at unity.gen.ModularUnitUnit.update(ModularUnitUnit.java:1840)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:59)
	at mindustry.gen.Groups.update(Groups.java:75)
	at mindustry.core.Logic.update(Logic.java:413)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:177)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:166)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:154)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:45)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

**Comment by StudioSharded** [comment]
![image](https://user-images.githubusercontent.com/98332856/152996795-7ff97bef-ac58-4a24-abf5-fc35103a22ba.png)
will be closure after this day.
