### ISSUE TITLE
Bugs somewhere from shafts

### ISSUE THREAD

**Issue by Hot-Sausage07** [AvantTeam/ProjectUnityPublic#38]
[crash-report-03_14_2022_14_07_28.txt](https://github.com/AvantTeam/ProjectUnityPublic/files/8242170/crash-report-03_14_2022_14_07_28.txt)

**Comment by Hot-Sausage07** [comment]
Mindustry has crashed. How unfortunate.
Version: pre-alpha build 135
OS: Windows 10 x64 (amd64)
Java Version: 1.8.0_72
Mods: test-utils:36, unity:0.1

java.lang.NullPointerException
	at unity.world.blocks.production.CrucibleChannel$CrucibleChannelBuild.draw(CrucibleChannel.java:69)
	at mindustry.gen.Building.payloadDraw(Building.java:385)
	at mindustry.world.blocks.payloads.BuildPayload.draw(BuildPayload.java:97)
	at mindustry.world.blocks.payloads.PayloadBlock$PayloadBlockBuild.drawPayload(PayloadBlock.java:226)
	at mindustry.world.blocks.payloads.PayloadSource$PayloadSourceBuild.draw(PayloadSource.java:140)
	at mindustry.world.Block.drawBase(Block.java:301)
	at mindustry.graphics.BlockRenderer.drawBlocks(BlockRenderer.java:347)
	at mindustry.core.Renderer.draw(Renderer.java:318)
	at mindustry.core.Renderer.update(Renderer.java:183)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:177)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:166)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:154)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:45)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

**Comment by Hot-Sausage07** [comment]
this is at the server, im with sharded

**Comment by StudioSharded** [comment]
yes

**Comment by StudioSharded** [comment]
server not crash..

**Comment by StudioSharded** [comment]
but it crash game

**Comment by StudioSharded** [comment]
i was firstly reported a bug

**Comment by Xeloboyo** [comment]
Should be fixed in next commit
