### ISSUE TITLE
Crash Toggling Belts at Editor

### ISSUE THREAD

**Issue by Hot-Sausage07** [AvantTeam/ProjectUnityPublic#48]
Toggling invisible linked belts after quitting and entering the editor
Have you edit in game
Yes, then deleting the partnered belt, and clicking the another belt
```
Mindustry has crashed. How unfortunate.
Version: pre-alpha build 135.2
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Mods: unity:0.1-youngcha.2.8

java.lang.NullPointerException: Cannot read field "x" because "b" is null
	at unity.world.blocks.distribution.DriveBelt$DriveBeltBuild.drawSelect(DriveBelt.java:240)
	at mindustry.graphics.OverlayRenderer.drawTop(OverlayRenderer.java:208)
	at arc.graphics.g2d.SortedSpriteBatch.flushRequests(SortedSpriteBatch.java:117)
	at arc.graphics.g2d.SortedSpriteBatch.flush(SortedSpriteBatch.java:97)
	at arc.graphics.g2d.Draw.flush(Draw.java:362)
	at mindustry.core.Renderer.draw(Renderer.java:323)
	at mindustry.core.Renderer.update(Renderer.java:183)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:177)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:166)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:154)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:45)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

```
[crash-report-04_14_2022_20_39_57.txt](https://github.com/AvantTeam/ProjectUnityPublic/files/8489265/crash-report-04_14_2022_20_39_57.txt)

**Comment by Hot-Sausage07** [comment]
[crash-report-04_14_2022_20_39_57.txt](https://github.com/AvantTeam/ProjectUnityPublic/files/8489254/crash-report-04_14_2022_20_39_57.txt)

**Comment by Hot-Sausage07** [comment]
bro sorry for another issue

**Comment by Xeloboyo** [comment]
thanks, should be resolved next update
